FROM jenkins/jenkins:lts
USER root
RUN apt-get update && apt install -y build-essential zlib1g-dev libncurses5-dev libgdbm-dev libnss3-dev libssl-dev libreadline-dev libffi-dev curl libbz2-dev
ADD Python-3.7.3.tar.xz /
